name: Auto Fetch drm-channels-events

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          MAIN_API_URL: ${{ secrets.MAIN_API_URL }}
          DECODE_API_URL: ${{ secrets.DECODE_API_URL }}
          STREAM_BASE_URL: ${{ secrets.STREAM_BASE_URL }}
        run: python main.py

      - name: Commit and Push generated JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update drm-channels-events"
          branch: main
