name: Auto Fetch drm-channels-events

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          MAIN_API_URL: ${{ secrets.MAIN_API_URL }}
          DECODE_API_URL: ${{ secrets.DECODE_API_URL }}
          STREAM_BASE_URL: ${{ secrets.STREAM_BASE_URL }}
          SECOND_API_URL: ${{ secrets.SECOND_API_URL }}
          SECOND_STREAM_BASE: ${{ secrets.SECOND_STREAM_BASE }}
        run: python main.py

      - name: Commit and Push generated JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update drm-channels-events"
          branch: main
